require("dotenv").config();
const express = require("express");
const cors = require("cors");
const app = express();
app.use(cors());
app.use(express.json());
app.use("/api/auth", require("./routes/authRoutes"));
app.use("/api/dashboard", require("./routes/dashboardRoutes"));
app.use("/api/sales", require("./routes/salesRoutes"));
app.use("/api/projects", require("./routes/projectRoutes"));
app.use("/api/finance", require("./routes/financeRoutes"));
app.use("/api/odoo", require("./routes/odooRoutes"));
const PORT = process.env.PORT || 5000;
app.listen(PORT, "0.0.0.0", () => console.log(`Server Running On Port ${PORT}`));
